# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        cache: true
    - name: Restore dependencies
      run: dotnet restore --use-lock-file
    - name: Install Newtonsoft.Json
      run: dotnet add package Newtonsoft.Json
    - name: Install Microsoft.Windows.SDK.BuildTools
      run: dotnet add package Microsoft.Windows.SDK.BuildTools
    - name: Install Microsoft.WindowsAppSDK
      run: dotnet add package Microsoft.WindowsAppSDK
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal